spring:
  application:
    name: LabControl
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml
    default-schema: labs
    driver-class-name: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: local
  liquibase:
    contexts: local
  datasource:
    url: jdbc:postgresql://localhost:5432/labs
    username: postgres
    password: postgres
  jpa:
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  liquibase:
    contexts: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}