spring:
  application:
    name: LabControl
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml
    default-schema: lab_control
  profiles:
    active: ${LAB_ACTIVE_PROFILE:local}
  jpa:
    hibernate:
      ddl-auto: validate

security:
  starts: Bearer

---
spring:
  config:
    activate:
      on-profile: local
  liquibase:
    contexts: local
  datasource:
    url: jdbc:postgresql://localhost:5432/lab_control
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: lab_control

security:
  secret: secret
  lifetime: 36000

---
spring:
  config:
    activate:
      on-profile: prod
  liquibase:
    contexts: prod
  datasource:
    url: ${LAB_DB_URL}
    username: ${LAB_DB_USERNAME}
    password: ${LAB_DB_PASSWORD}

security:
  secret: ${LAB_AUTH_SECRET}
  lifetime: ${LAB_TOKEN_LIFE_TIME}