spring:
  application:
    name: LabControl
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml
    default-schema: labs
    driver-class-name: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: local
  liquibase:
    contexts: local
    url: jdbc:postgresql://localhost:5432/labs
    user: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/labs
    driver-class-name: org.postgresql.Driver


---
spring:
  config:
    activate:
      on-profile: production